
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov 27 2023 11:24:29 IST (Nov 27 2023 05:54:29 UTC)

// Verification Directory fv/ram 

module ram(clk, en, rw, data_in, address, data_out);
  input clk, en, rw;
  input [7:0] data_in;
  input [2:0] address;
  output [7:0] data_out;
  wire clk, en, rw;
  wire [7:0] data_in;
  wire [2:0] address;
  wire [7:0] data_out;
  wire [7:0] \memory[1] ;
  wire [7:0] \memory[3] ;
  wire [7:0] \memory[6] ;
  wire [7:0] \memory[2] ;
  wire [7:0] \memory[7] ;
  wire [7:0] \memory[4] ;
  wire [7:0] \memory[5] ;
  wire [7:0] \memory[0] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_55, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_144, n_145;
  OR2X1 g2536__8780(.A (n_89), .B (n_111), .Y (n_129));
  OR2X1 g2531__4296(.A (n_114), .B (n_106), .Y (n_128));
  OR2X1 g2535__3772(.A (n_82), .B (n_107), .Y (n_127));
  OR2X1 g2532__1474(.A (n_83), .B (n_116), .Y (n_126));
  OR2X1 g2533__4547(.A (n_96), .B (n_110), .Y (n_125));
  OR2X1 g2538__9682(.A (n_105), .B (n_121), .Y (n_124));
  OR2X1 g2537__2683(.A (n_119), .B (n_112), .Y (n_123));
  OR2X1 g2534__1309(.A (n_120), .B (n_108), .Y (n_122));
  OAI221XL g2541__6877(.A0 (n_113), .A1 (n_7), .B0 (n_115), .B1 (n_42),
       .C0 (n_103), .Y (n_121));
  OAI221XL g2549__2900(.A0 (n_118), .A1 (n_9), .B0 (n_117), .B1 (n_20),
       .C0 (n_88), .Y (n_120));
  OAI221XL g2550__2391(.A0 (n_118), .A1 (n_37), .B0 (n_117), .B1 (n_3),
       .C0 (n_91), .Y (n_119));
  OAI221XL g2542__7675(.A0 (n_115), .A1 (n_46), .B0 (n_117), .B1
       (n_45), .C0 (n_99), .Y (n_116));
  OAI221XL g2551__7118(.A0 (n_113), .A1 (n_41), .B0 (n_118), .B1 (n_8),
       .C0 (n_86), .Y (n_114));
  OAI221XL g2543__8757(.A0 (n_113), .A1 (n_6), .B0 (n_115), .B1 (n_44),
       .C0 (n_92), .Y (n_112));
  OAI221XL g2544__1786(.A0 (n_109), .A1 (n_18), .B0 (n_117), .B1
       (n_21), .C0 (n_94), .Y (n_111));
  OAI221XL g2539__5953(.A0 (n_109), .A1 (n_36), .B0 (n_90), .B1 (n_32),
       .C0 (n_98), .Y (n_110));
  OAI221XL g2545__5703(.A0 (n_113), .A1 (n_19), .B0 (n_115), .B1
       (n_31), .C0 (n_104), .Y (n_108));
  OAI221XL g2546__7114(.A0 (n_109), .A1 (n_25), .B0 (n_117), .B1
       (n_38), .C0 (n_85), .Y (n_107));
  OAI221XL g2540__5266(.A0 (n_115), .A1 (n_39), .B0 (n_117), .B1 (n_5),
       .C0 (n_95), .Y (n_106));
  OAI221XL g2588__2250(.A0 (n_118), .A1 (n_24), .B0 (n_117), .B1
       (n_13), .C0 (n_84), .Y (n_105));
  AOI222XL g2592__6083(.A0 (n_102), .A1 (\memory[1] [5]), .B0
       (\memory[3] [5]), .B1 (n_101), .C0 (\memory[6] [5]), .C1
       (n_100), .Y (n_104));
  AOI222XL g2589__2703(.A0 (n_102), .A1 (\memory[1] [3]), .B0
       (\memory[3] [3]), .B1 (n_101), .C0 (\memory[6] [3]), .C1
       (n_100), .Y (n_103));
  AOI222XL g2590__5795(.A0 (n_144), .A1 (\memory[2] [4]), .B0
       (\memory[1] [4]), .B1 (n_102), .C0 (\memory[6] [4]), .C1
       (n_100), .Y (n_99));
  AOI222XL g2591__7344(.A0 (n_144), .A1 (\memory[2] [1]), .B0
       (\memory[3] [1]), .B1 (n_101), .C0 (\memory[7] [1]), .C1 (n_93),
       .Y (n_98));
  OAI221XL g2548__1840(.A0 (n_118), .A1 (n_48), .B0 (n_117), .B1
       (n_33), .C0 (n_72), .Y (n_96));
  AOI222XL g2593__5019(.A0 (n_102), .A1 (\memory[1] [0]), .B0
       (\memory[3] [0]), .B1 (n_101), .C0 (\memory[6] [0]), .C1
       (n_100), .Y (n_95));
  AOI222XL g2594__1857(.A0 (n_144), .A1 (\memory[2] [6]), .B0
       (\memory[3] [6]), .B1 (n_101), .C0 (\memory[7] [6]), .C1 (n_93),
       .Y (n_94));
  AOI222XL g2595__9906(.A0 (n_102), .A1 (\memory[1] [2]), .B0
       (\memory[3] [2]), .B1 (n_101), .C0 (\memory[6] [2]), .C1
       (n_100), .Y (n_92));
  OA22X1 g2632__8780(.A0 (n_87), .A1 (n_16), .B0 (n_90), .B1 (n_43), .Y
       (n_91));
  OAI221XL g2552__4296(.A0 (n_113), .A1 (n_26), .B0 (n_118), .B1 (n_2),
       .C0 (n_69), .Y (n_89));
  OA22X1 g2627__3772(.A0 (n_87), .A1 (n_40), .B0 (n_90), .B1 (n_22), .Y
       (n_88));
  OA22X1 g2631__1474(.A0 (n_87), .A1 (n_12), .B0 (n_90), .B1 (n_28), .Y
       (n_86));
  AOI222XL g2596__4547(.A0 (n_144), .A1 (\memory[2] [7]), .B0
       (\memory[1] [7]), .B1 (n_102), .C0 (\memory[7] [7]), .C1 (n_93),
       .Y (n_85));
  OA22X1 g2634__9682(.A0 (n_87), .A1 (n_1), .B0 (n_90), .B1 (n_35), .Y
       (n_84));
  OAI221XL g2547__2683(.A0 (n_113), .A1 (n_4), .B0 (n_118), .B1 (n_30),
       .C0 (n_71), .Y (n_83));
  OAI221XL g2587__1309(.A0 (n_113), .A1 (n_17), .B0 (n_118), .B1 (n_0),
       .C0 (n_73), .Y (n_82));
  EDFFHQX2 \memory_reg[1][4] (.CK (clk), .D (data_in[4]), .E (n_80), .Q
       (\memory[1] [4]));
  EDFFHQX2 \memory_reg[1][0] (.CK (clk), .D (data_in[0]), .E (n_80), .Q
       (\memory[1] [0]));
  EDFFHQX2 \memory_reg[1][3] (.CK (clk), .D (data_in[3]), .E (n_80), .Q
       (\memory[1] [3]));
  EDFFHQX2 \memory_reg[1][5] (.CK (clk), .D (data_in[5]), .E (n_80), .Q
       (\memory[1] [5]));
  EDFFHQX2 \memory_reg[1][2] (.CK (clk), .D (data_in[2]), .E (n_80), .Q
       (\memory[1] [2]));
  EDFFHQX2 \memory_reg[3][1] (.CK (clk), .D (data_in[1]), .E (n_78), .Q
       (\memory[3] [1]));
  EDFFHQX2 \memory_reg[1][7] (.CK (clk), .D (data_in[7]), .E (n_80), .Q
       (\memory[1] [7]));
  EDFFHQX2 \memory_reg[2][1] (.CK (clk), .D (data_in[1]), .E (n_77), .Q
       (\memory[2] [1]));
  EDFFHQX2 \memory_reg[2][4] (.CK (clk), .D (data_in[4]), .E (n_77), .Q
       (\memory[2] [4]));
  EDFFHQX2 \memory_reg[7][7] (.CK (clk), .D (data_in[7]), .E (n_76), .Q
       (\memory[7] [7]));
  EDFFHQX2 \memory_reg[2][6] (.CK (clk), .D (data_in[6]), .E (n_77), .Q
       (\memory[2] [6]));
  EDFFHQX2 \memory_reg[2][7] (.CK (clk), .D (data_in[7]), .E (n_77), .Q
       (\memory[2] [7]));
  EDFFHQX2 \memory_reg[3][0] (.CK (clk), .D (data_in[0]), .E (n_78), .Q
       (\memory[3] [0]));
  EDFFHQX2 \memory_reg[3][2] (.CK (clk), .D (data_in[2]), .E (n_78), .Q
       (\memory[3] [2]));
  EDFFHQX2 \memory_reg[3][3] (.CK (clk), .D (data_in[3]), .E (n_78), .Q
       (\memory[3] [3]));
  EDFFHQX2 \memory_reg[3][6] (.CK (clk), .D (data_in[6]), .E (n_78), .Q
       (\memory[3] [6]));
  EDFFHQX2 \memory_reg[6][4] (.CK (clk), .D (data_in[4]), .E (n_75), .Q
       (\memory[6] [4]));
  EDFFHQX2 \memory_reg[6][0] (.CK (clk), .D (data_in[0]), .E (n_75), .Q
       (\memory[6] [0]));
  EDFFHQX2 \memory_reg[6][2] (.CK (clk), .D (data_in[2]), .E (n_75), .Q
       (\memory[6] [2]));
  EDFFHQX2 \memory_reg[6][3] (.CK (clk), .D (data_in[3]), .E (n_75), .Q
       (\memory[6] [3]));
  EDFFHQX2 \memory_reg[6][5] (.CK (clk), .D (data_in[5]), .E (n_75), .Q
       (\memory[6] [5]));
  EDFFHQX2 \memory_reg[3][5] (.CK (clk), .D (data_in[5]), .E (n_78), .Q
       (\memory[3] [5]));
  EDFFHQX2 \memory_reg[7][1] (.CK (clk), .D (data_in[1]), .E (n_76), .Q
       (\memory[7] [1]));
  EDFFHQX2 \memory_reg[7][6] (.CK (clk), .D (data_in[6]), .E (n_76), .Q
       (\memory[7] [6]));
  OA22X1 g2630__6877(.A0 (n_70), .A1 (n_34), .B0 (n_90), .B1 (n_29), .Y
       (n_73));
  OA22X1 g2629__2900(.A0 (n_113), .A1 (n_14), .B0 (n_68), .B1 (n_27),
       .Y (n_72));
  OA22X1 g2628__2391(.A0 (n_70), .A1 (n_10), .B0 (n_90), .B1 (n_15), .Y
       (n_71));
  OA22X1 g2633__7675(.A0 (n_68), .A1 (n_47), .B0 (n_90), .B1 (n_23), .Y
       (n_69));
  INVXL g2646(.A (n_100), .Y (n_109));
  INVXL g2636(.A (n_144), .Y (n_87));
  INVXL g2647(.A (n_93), .Y (n_115));
  INVXL g2645(.A (n_70), .Y (n_101));
  AND2X2 g2651__7118(.A (n_66), .B (n_67), .Y (n_100));
  AND2X2 g2653__8757(.A (n_62), .B (n_67), .Y (n_93));
  INVXL g2635(.A (n_68), .Y (n_102));
  OR2X2 g2649__5953(.A (n_52), .B (n_65), .Y (n_70));
  OR2X2 g2648__5703(.A (n_61), .B (n_63), .Y (n_90));
  OR2X2 g2650__7114(.A (n_64), .B (n_65), .Y (n_113));
  OR2X2 g2652__5266(.A (n_64), .B (n_63), .Y (n_118));
  AND2X2 g2654__2250(.A (n_58), .B (n_59), .Y (n_81));
  AND2X2 g2655__6083(.A (n_62), .B (n_60), .Y (n_78));
  OR2X2 g2637__2703(.A (n_61), .B (n_65), .Y (n_68));
  AND2X2 g2639__5795(.A (n_57), .B (n_60), .Y (n_79));
  AND2X2 g2640__7344(.A (n_66), .B (n_59), .Y (n_75));
  AND2X2 g2641__1840(.A (n_62), .B (n_59), .Y (n_76));
  AND2X2 g2642__5019(.A (n_58), .B (n_60), .Y (n_80));
  AND2X2 g2643__1857(.A (n_57), .B (n_59), .Y (n_74));
  AND2X2 g2644__9906(.A (n_66), .B (n_60), .Y (n_77));
  INVXL g2659(.A (n_63), .Y (n_67));
  OR2X2 g2657__8780(.A (address[2]), .B (n_145), .Y (n_65));
  AND2X2 g2658__4296(.A (n_55), .B (n_53), .Y (n_60));
  OR2X2 g2661__3772(.A (n_55), .B (n_145), .Y (n_63));
  AND2X2 g2660__1474(.A (address[2]), .B (n_53), .Y (n_59));
  INVXL g2666(.A (n_52), .Y (n_62));
  INVXL g2662(.A (n_145), .Y (n_117));
  INVXL g2667(.A (n_57), .Y (n_64));
  INVXL g2668(.A (n_58), .Y (n_61));
  OR2X1 g2669__4547(.A (n_49), .B (n_51), .Y (n_52));
  AND2X2 g2664__2683(.A (address[1]), .B (n_51), .Y (n_66));
  AND2X1 g2663__1309(.A (en), .B (n_50), .Y (n_53));
  AND2X2 g2671__6877(.A (address[0]), .B (n_49), .Y (n_58));
  AND2X2 g2670__2900(.A (n_51), .B (n_49), .Y (n_57));
  INVXL g2723(.A (address[2]), .Y (n_55));
  INVXL g2721(.A (rw), .Y (n_50));
  INVXL g2724(.A (address[0]), .Y (n_51));
  INVXL g2697(.A (address[1]), .Y (n_49));
  EDFFX1 \memory_reg[4][1] (.CK (clk), .D (data_in[1]), .E (n_74), .Q
       (\memory[4] [1]), .QN (n_48));
  EDFFX1 \memory_reg[1][6] (.CK (clk), .D (data_in[6]), .E (n_80), .Q
       (\memory[1] [6]), .QN (n_47));
  EDFFX1 \memory_reg[7][4] (.CK (clk), .D (data_in[4]), .E (n_76), .Q
       (\memory[7] [4]), .QN (n_46));
  DFFX2 \data_out_reg[4] (.CK (clk), .D (n_126), .Q (data_out[4]), .QN
       (n_45));
  EDFFX1 \memory_reg[7][2] (.CK (clk), .D (data_in[2]), .E (n_76), .Q
       (\memory[7] [2]), .QN (n_44));
  EDFFX1 \memory_reg[5][2] (.CK (clk), .D (data_in[2]), .E (n_81), .Q
       (\memory[5] [2]), .QN (n_43));
  EDFFX1 \memory_reg[7][3] (.CK (clk), .D (data_in[3]), .E (n_76), .Q
       (\memory[7] [3]), .QN (n_42));
  EDFFX1 \memory_reg[0][0] (.CK (clk), .D (data_in[0]), .E (n_79), .Q
       (\memory[0] [0]), .QN (n_41));
  EDFFX1 \memory_reg[2][5] (.CK (clk), .D (data_in[5]), .E (n_77), .Q
       (\memory[2] [5]), .QN (n_40));
  EDFFX1 \memory_reg[7][0] (.CK (clk), .D (data_in[0]), .E (n_76), .Q
       (\memory[7] [0]), .QN (n_39));
  DFFX2 \data_out_reg[7] (.CK (clk), .D (n_127), .Q (data_out[7]), .QN
       (n_38));
  EDFFX1 \memory_reg[4][2] (.CK (clk), .D (data_in[2]), .E (n_74), .Q
       (\memory[4] [2]), .QN (n_37));
  EDFFX1 \memory_reg[6][1] (.CK (clk), .D (data_in[1]), .E (n_75), .Q
       (\memory[6] [1]), .QN (n_36));
  EDFFX1 \memory_reg[5][3] (.CK (clk), .D (data_in[3]), .E (n_81), .Q
       (\memory[5] [3]), .QN (n_35));
  EDFFX1 \memory_reg[3][7] (.CK (clk), .D (data_in[7]), .E (n_78), .Q
       (\memory[3] [7]), .QN (n_34));
  DFFX2 \data_out_reg[1] (.CK (clk), .D (n_125), .Q (data_out[1]), .QN
       (n_33));
  EDFFX1 \memory_reg[5][1] (.CK (clk), .D (data_in[1]), .E (n_81), .Q
       (\memory[5] [1]), .QN (n_32));
  EDFFX1 \memory_reg[7][5] (.CK (clk), .D (data_in[5]), .E (n_76), .Q
       (\memory[7] [5]), .QN (n_31));
  EDFFX1 \memory_reg[4][4] (.CK (clk), .D (data_in[4]), .E (n_74), .Q
       (\memory[4] [4]), .QN (n_30));
  EDFFX1 \memory_reg[5][7] (.CK (clk), .D (data_in[7]), .E (n_81), .Q
       (\memory[5] [7]), .QN (n_29));
  EDFFX1 \memory_reg[5][0] (.CK (clk), .D (data_in[0]), .E (n_81), .Q
       (\memory[5] [0]), .QN (n_28));
  EDFFX1 \memory_reg[1][1] (.CK (clk), .D (data_in[1]), .E (n_80), .Q
       (\memory[1] [1]), .QN (n_27));
  EDFFX1 \memory_reg[0][6] (.CK (clk), .D (data_in[6]), .E (n_79), .Q
       (\memory[0] [6]), .QN (n_26));
  EDFFX1 \memory_reg[6][7] (.CK (clk), .D (data_in[7]), .E (n_75), .Q
       (\memory[6] [7]), .QN (n_25));
  EDFFX1 \memory_reg[4][3] (.CK (clk), .D (data_in[3]), .E (n_74), .Q
       (\memory[4] [3]), .QN (n_24));
  EDFFX1 \memory_reg[5][6] (.CK (clk), .D (data_in[6]), .E (n_81), .Q
       (\memory[5] [6]), .QN (n_23));
  EDFFX1 \memory_reg[5][5] (.CK (clk), .D (data_in[5]), .E (n_81), .Q
       (\memory[5] [5]), .QN (n_22));
  DFFX2 \data_out_reg[6] (.CK (clk), .D (n_129), .Q (data_out[6]), .QN
       (n_21));
  DFFX2 \data_out_reg[5] (.CK (clk), .D (n_122), .Q (data_out[5]), .QN
       (n_20));
  EDFFX1 \memory_reg[0][5] (.CK (clk), .D (data_in[5]), .E (n_79), .Q
       (\memory[0] [5]), .QN (n_19));
  EDFFX1 \memory_reg[6][6] (.CK (clk), .D (data_in[6]), .E (n_75), .Q
       (\memory[6] [6]), .QN (n_18));
  EDFFX1 \memory_reg[0][7] (.CK (clk), .D (data_in[7]), .E (n_79), .Q
       (\memory[0] [7]), .QN (n_17));
  EDFFX1 \memory_reg[2][2] (.CK (clk), .D (data_in[2]), .E (n_77), .Q
       (\memory[2] [2]), .QN (n_16));
  EDFFX1 \memory_reg[5][4] (.CK (clk), .D (data_in[4]), .E (n_81), .Q
       (\memory[5] [4]), .QN (n_15));
  EDFFX1 \memory_reg[0][1] (.CK (clk), .D (data_in[1]), .E (n_79), .Q
       (\memory[0] [1]), .QN (n_14));
  DFFX2 \data_out_reg[3] (.CK (clk), .D (n_124), .Q (data_out[3]), .QN
       (n_13));
  EDFFX1 \memory_reg[2][0] (.CK (clk), .D (data_in[0]), .E (n_77), .Q
       (\memory[2] [0]), .QN (n_12));
  EDFFX1 \memory_reg[3][4] (.CK (clk), .D (data_in[4]), .E (n_78), .Q
       (\memory[3] [4]), .QN (n_10));
  EDFFX1 \memory_reg[4][5] (.CK (clk), .D (data_in[5]), .E (n_74), .Q
       (\memory[4] [5]), .QN (n_9));
  EDFFX1 \memory_reg[4][0] (.CK (clk), .D (data_in[0]), .E (n_74), .Q
       (\memory[4] [0]), .QN (n_8));
  EDFFX1 \memory_reg[0][3] (.CK (clk), .D (data_in[3]), .E (n_79), .Q
       (\memory[0] [3]), .QN (n_7));
  EDFFX1 \memory_reg[0][2] (.CK (clk), .D (data_in[2]), .E (n_79), .Q
       (\memory[0] [2]), .QN (n_6));
  DFFX2 \data_out_reg[0] (.CK (clk), .D (n_128), .Q (data_out[0]), .QN
       (n_5));
  EDFFX1 \memory_reg[0][4] (.CK (clk), .D (data_in[4]), .E (n_79), .Q
       (\memory[0] [4]), .QN (n_4));
  DFFX2 \data_out_reg[2] (.CK (clk), .D (n_123), .Q (data_out[2]), .QN
       (n_3));
  EDFFX1 \memory_reg[4][6] (.CK (clk), .D (data_in[6]), .E (n_74), .Q
       (\memory[4] [6]), .QN (n_2));
  EDFFX1 \memory_reg[2][3] (.CK (clk), .D (data_in[3]), .E (n_77), .Q
       (\memory[2] [3]), .QN (n_1));
  EDFFX1 \memory_reg[4][7] (.CK (clk), .D (data_in[7]), .E (n_74), .Q
       (\memory[4] [7]), .QN (n_0));
  NOR2BX4 g2(.AN (n_66), .B (n_65), .Y (n_144));
  NAND2BX4 g2893(.AN (n_50), .B (en), .Y (n_145));
endmodule

